### ISSUE TITLE
Profile creation with Programming Languages skip 1 index in DB

### ISSUE THREAD

**Issue by daniellaera** [daniellaera/supabase-react-auth#2]
when creating the first profile, add 4 languages in pick list, the actual drop in db creates only 3 items, skipping the second actual item at index 1; look at prisma request in backend, profile.ts file in api/ folder

**Comment by ishaanparlikar** [comment]
Hi, I am trying to work on this issue. But I am getting error setting up supabase env. Could you help me with it?

**Comment by daniellaera** [comment]
Hi @ishaanparlikar and thank you a lot for taking time for this issue. As I wrote in the root README, you need to have `.env` files in backend and frontend folders.
For backend you need in your .env file the following value: `DATABASE_URL="postgresql://postgres:postgres@localhost:5432/supabase_react_auth_db?schema=public"`
this represents my local docker postgres database, it depends on how you run yours.
In frontend folder you need 2 values in the .env:
REACT_APP_SUPABASE_URL which corresponds to your supabase app URL
REACT_APP_SUPABASE_ANON_KEY also corresponds to your supabase application ANON KEY

**Comment by daniellaera** [comment]
thank you again, fixed in this issue https://github.com/daniellaera/supabase-react-auth/commit/db4a4b1d69d8d779ec31926bdff3dd3444d114bc
